Portfolio mobile changes.
jdbs9514/Portfolio-setup-and-mobile-version-skeleton pull request #4
Opened 2022-05-31 06:41 UTC by jdbs9514

2022-05-31 19:10 UTC, tufoinnkuo10 requested changes
Hi @jdbs9514  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⛔ 🔴 🟥 

You have submitted a project, that requires the following;
- [ ] please add a good pull request summary of what you have done
- [ ] default branch should be the main branch, you can check how to change that [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request)
- [ ] please use the correct [README](https://github.com/microverseinc/readme-template/blob/master/README.md) TEMPLATE.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-05-31 21:42 UTC, youmari requested changes
Hi @jdbs9514 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that 
- doesn't have a descriptive short summary please try to add one that tells in more detail what you've done in you Pull Request 
![image](https://user-images.githubusercontent.com/61790587/171289249-97cf5497-e507-4176-a7cc-089cb66fbe1b.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-06-01 00:14 UTC, keneogu requested changes
Hi @jdbs9514, 

Good job so far!

- Linters are working
- well structured codes

There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️

- [ ] Your hamburger menu is outside the mobile version design
![screen2](https://user-images.githubusercontent.com/53356820/171303230-8ae32f77-f51a-4c03-8400-a8ba3366ff36.png)

- [ ] Please add the background color and follow the Figma design
Your design
![screen1](https://user-images.githubusercontent.com/53356820/171303613-5be4a31d-da8b-4370-8939-55189a770347.png).
figma design
![screen1a](https://user-images.githubusercontent.com/53356820/171303656-f669b2df-66ba-423e-91ce-392110f342cf.png)



_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

2022-06-01 00:14 UTC, keneogu commented on index.html
> +        LET´S CONNECT
- [ ] Let's connect is a title. Make use of `hx` tag.

2022-06-01 00:14 UTC, keneogu commented on index.html
> +     <h2>Languajes
- [ ] From the project specification, The technology categories ("Languages", "Frameworks" and "Skills") should be wrapped in a `ul` tag, and each of them in `li` tag.

2022-06-01 00:14 UTC, keneogu commented on index.html
> +        Frameworks
- [ ] From the project specification, The technology categories ("Languages", "Frameworks" and "Skills") should be wrapped in a `ul` tag, and each of them in `li` tag.

2022-06-01 00:14 UTC, keneogu commented on index.html
> +        Skills
- [ ] From the project specification, The technology categories ("Languages", "Frameworks" and "Skills") should be wrapped in a `ul` tag, and each of them in `li` tag.

2022-06-01 15:46 UTC, dasileker approved these changes
### **Hi @jdbs9514,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-01 15:49 UTC, merged